### ISSUE TITLE
wp commands run in lando when wp is run against a remote

### ISSUE THREAD

**Issue by slam-campup** [JoshuaBedford/lando-zsh#5]
`wp option get home --ssh=my_remote` attempts to execute inside lando and fails. 

This is because lando by default does not import the `.ssh/config` file and so lando has no knowlege of host aliases. 

When --ssh flag is used, wp commands should not be prefixed as `lando wp`.

**Comment by JoshuaBedford** [comment]
Feel free to submit a PR and I can review it, but I no longer use Lando full time and don't have the time currently to dedicate to working on this project.

Edit: another option could be forking this and making changes for your specific environment yourself, since updates to this repo will be rare if at all.
